### ISSUE TITLE
m3u generated but no longer plays in vlc

### ISSUE THREAD

**Issue by vortex91** [schwifty42069/pmg#10]
do we need to configure vlc player to work with this m3u? or is there some other way to get this m3u8 to work?

**Comment by vortex91** [comment]
ignore above comment.  I was doing some post processing and did not pass some of the correct edits (for header info)   it works perfect as is

**Comment by schwifty42069** [comment]
You're lucky you have it working in VLC. Most of the versions I have seen have a flaw in their HLS implementation that makes the #EXTVLCOPT directive only last for the initial call to the playlist, when it tried to go grab the chunks it resorts back to the VLC user-agent header and is thus blocked by the host ):

Glad it's working though! If it ever stops working in VLC I recommend MPV.

Enjoy!

**Comment by vortex91** [comment]
You are correct.  I was setting the header manually in VLC to get it to
work (advanced option during network play back.)  Using automated way it
does not work.  However the main purpose i use your script is to post
process my own m3u8 (forwarding to tokens generated by yoru script every 5
min) using kodi iptv simpler client. Feel free to use my link for your
personal use but please do not release to public
http://vortex91.000webhostapp.com/armeniaUS is the m3u8.  first 89 channels
are from your script
http://vortex91.000webhostapp.com/guide.xml is the guide to go along with
it.

**Comment by dorrance** [comment]
I can give you access to a server if you like

**Comment by vortex91** [comment]
is it full access?  or just ftp? are redicrect allowed?

**Comment by dorrance** [comment]
Send me email baneccloud@gmail.com

**Comment by milo123milo** [comment]
@vortex91 Hi. I'm wondering if you could maybe give me some directions on making "rehosted" or postprocessed list with forwarded tokens. Thanks, i hope you will reply someday. Best regards.
