### ISSUE TITLE
session id added to ustvgo

### ISSUE THREAD

**Issue by vortex91** [schwifty42069/pmg#11]
https://peer2.ustv.to/Animal/myStream/chunks.m3u8?nimblesessionid=95112513&wmsAuthSign=

**Comment by schwifty42069** [comment]
Yeah they added a full blown WAF so it'll be a bit before I can patch it. That session-id is from their nimble server, it's always been in calls to the chunklist. The real issue is going to be getting around their firewall and avoid captcha.

**Comment by vortex91** [comment]
K got it figured out.  They added iframe.  change code in line 56
from 
        self.renew_token_node = 'http://ustvgo.tv/nfl-network-live-free'
to
        self.renew_token_node = 'https://ustvgo.tv/player.php?stream=AE'

will fix issue

**Comment by schwifty42069** [comment]
@vortex91 I see what you're saying, but I'm still getting stuck by the WAF.

**Comment by vortex91** [comment]
Even if you use my m3u8 i gave you?

**Comment by schwifty42069** [comment]
@vortex nevermind, adding a user-agent header completely bypasses the WAF if you use the iframe link. This is great, no more selenium required for now! Woohoooo!

**Comment by schwifty42069** [comment]
@vortex91 The script will be like 1000x faster now too since I won't need selenium. :D

**Comment by vortex91** [comment]
:) iv been running it that way for a while now.  feeding that ccloud also :).  Also the CW is incorect in code change it from CWE to CW

**Comment by schwifty42069** [comment]
aaaaaaaaaaaaaaand we're patched!
