### ISSUE TITLE
Error while running the script

### ISSUE THREAD

**Issue by tobedev** [schwifty42069/pmg#2]
**Having the following error while running the script:**

`$ python3.7 -m piptv_pmg.pmg -o channels.m3u

Detected Linux...
Working some black magic..

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/still/pmg/piptv_pmg/pmg.py", line 156, in <module>
    main(sys.argv[1:])
  File "/home/still/pmg/piptv_pmg/pmg.py", line 149, in main
    mw.retrieve_new_token()
  File "/home/still/pmg/piptv_pmg/pmg.py", line 103, in retrieve_new_token
    req = self.driver.execute_script(self.export_har_js)
  File "/home/still/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/still/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/still/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: ReferenceError: HAR is not defined`

**Also here's the geckodriver.log contents in case it may help:**

`1570302520111	mozrunner::runner	INFO	Running command: "/usr/local/bin/firefox" "-marionette" "-headless" "-devtools" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileAPJeQa"
Dark Theme Override
*** You are running in headless mode.
1570302520408	addons.xpi-utils	WARN	Add-on harexporttrigger@getfirebug.com is not correctly signed.
1570302520408	addons.xpi-utils	WARN	Add-on harexporttrigger@getfirebug.com is not correctly signed.
1570302520408	addons.xpi-utils	WARN	addMetadata: Add-on harexporttrigger@getfirebug.com is invalid: Error: Extension harexporttrigger@getfirebug.com is not correctly signed(resource://gre/modules/addons/XPIDatabase.jsm:2725:15) JS Stack trace: addMetadata@XPIDatabase.jsm:2725:15
processFileChanges@XPIDatabase.jsm:3152:26
checkForChanges@XPIProvider.jsm:2946:55
startup@XPIProvider.jsm:2406:12
callProvider@AddonManager.jsm:213:31
_startProvider@AddonManager.jsm:649:5
startup@AddonManager.jsm:873:14
startup@AddonManager.jsm:3469:26
observe@addonManager.js:86:29
1570302520427	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1570302520428	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1570302520428	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1570302520428	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1570302522270	Marionette	INFO	Listening on port 41311
1570302522320	Marionette	WARN	TLS certificate errors will be ignored for this session
console.error: "Error while calling actor 'pagestyle's method 'getLayout'" "can't access dead object"
console.error: "getLayout@resource://devtools/server/actors/styles.js:921:24\nhandler@resource://devtools/shared/protocol/Actor.js:154:37\nonPacket@resource://devtools/server/main.js:1402:58\nreceiveMessage@resource://devtools/shared/transport/child-transport.js:66:16\n"
console.error: "Protocol error (unknownError): can't access dead object"
console.error: "Error while calling actor 'layout's method 'getGrids'" "node is null"
console.error: "getGrids@resource://devtools/server/actors/layout.js:501:26\ngetGrids@resource://devtools/server/actors/layout.js:506:43\ngetGrids@resource://devtools/server/actors/layout.js:506:43\ngetGrids@resource://devtools/server/actors/layout.js:506:43\nhandler@resource://devtools/shared/protocol/Actor.js:154:37\nonPacket@resource://devtools/server/main.js:1402:58\nreceiveMessage@resource://devtools/shared/transport/child-transport.js:66:16\n"
console.error: "Error while calling actor 'layout's method 'getGrids'" "node is null"
console.error: "getGrids@resource://devtools/server/actors/layout.js:501:26\ngetGrids@resource://devtools/server/actors/layout.js:506:43\ngetGrids@resource://devtools/server/actors/layout.js:506:43\ngetGrids@resource://devtools/server/actors/layout.js:506:43\nhandler@resource://devtools/shared/protocol/Actor.js:154:37\nonPacket@resource://devtools/server/main.js:1402:58\nreceiveMessage@resource://devtools/shared/transport/child-transport.js:66:16\n"
console.error: "Error while calling actor 'layout's method 'getGrids'" "node is null"
console.error: "getGrids@resource://devtools/server/actors/layout.js:501:26\ngetGrids@resource://devtools/server/actors/layout.js:506:43\ngetGrids@resource://devtools/server/actors/layout.js:506:43\ngetGrids@resource://devtools/server/actors/layout.js:506:43\nhandler@resource://devtools/shared/protocol/Actor.js:154:37\nonPacket@resource://devtools/server/main.js:1402:58\nreceiveMessage@resource://devtools/shared/transport/child-transport.js:66:16\n"
console.error: "Error while calling actor 'layout's method 'getGrids'" "node is null"
console.error: "getGrids@resource://devtools/server/actors/layout.js:501:26\ngetGrids@resource://devtools/server/actors/layout.js:506:43\ngetGrids@resource://devtools/server/actors/layout.js:506:43\ngetGrids@resource://devtools/server/actors/layout.js:506:43\nhandler@resource://devtools/shared/protocol/Actor.js:154:37\nonPacket@resource://devtools/server/main.js:1402:58\nreceiveMessage@resource://devtools/shared/transport/child-transport.js:66:16\n"
console.error: "Error while calling actor 'layout's method 'getGrids'" "node is null"
console.error: "getGrids@resource://devtools/server/actors/layout.js:501:26\ngetGrids@resource://devtools/server/actors/layout.js:506:43\ngetGrids@resource://devtools/server/actors/layout.js:506:43\ngetGrids@resource://devtools/server/actors/layout.js:506:43\nhandler@resource://devtools/shared/protocol/Actor.js:154:37\nonPacket@resource://devtools/server/main.js:1402:58\nreceiveMessage@resource://devtools/shared/transport/child-transport.js:66:16\n"
console.error: "Error while calling actor 'layout's method 'getGrids'" "node is null"
console.error: "getGrids@resource://devtools/server/actors/layout.js:501:26\ngetGrids@resource://devtools/server/actors/layout.js:506:43\ngetGrids@resource://devtools/server/actors/layout.js:506:43\ngetGrids@resource://devtools/server/actors/layout.js:506:43\nhandler@resource://devtools/shared/protocol/Actor.js:154:37\nonPacket@resource://devtools/server/main.js:1402:58\nreceiveMessage@resource://devtools/shared/transport/child-transport.js:66:16\n"
console.error: "Error while calling actor 'layout's method 'getGrids'" "node is null"
console.error: "getGrids@resource://devtools/server/actors/layout.js:501:26\ngetGrids@resource://devtools/server/actors/layout.js:506:43\ngetGrids@resource://devtools/server/actors/layout.js:506:43\ngetGrids@resource://devtools/server/actors/layout.js:506:43\nhandler@resource://devtools/shared/protocol/Actor.js:154:37\nonPacket@resource://devtools/server/main.js:1402:58\nreceiveMessage@resource://devtools/shared/transport/child-transport.js:66:16\n"
console.error: "Error while calling actor 'layout's method 'getGrids'" "node is null"
console.error: "getGrids@resource://devtools/server/actors/layout.js:501:26\ngetGrids@resource://devtools/server/actors/layout.js:506:43\ngetGrids@resource://devtools/server/actors/layout.js:506:43\ngetGrids@resource://devtools/server/actors/layout.js:506:43\nhandler@resource://devtools/shared/protocol/Actor.js:154:37\nonPacket@resource://devtools/server/main.js:1402:58\nreceiveMessage@resource://devtools/shared/transport/child-transport.js:66:16\n"`

**Comment by schwifty42069** [comment]
This error is because it's not seeing the HAR export trigger addon.. Weird. This is with a pip install?

**Comment by schwifty42069** [comment]
Do you mind if I ask you to modify the script directly for me so I don't have to push commits to have you test it? I can't reproduce it, but I think I can fix it for you by having you stick a one liner in the script

**Comment by schwifty42069** [comment]
at line 62 in the script try pasting this in there and running it again:

```
self.driver.install_addon(self.resource_dir + "har_export_trigger-0.6.1.xpi", temporary=True)
```

I have only seen this be required for windows, but perhaps some Linux distros need it too. If this fixes it I will push a commit to add it, even if it's a bit redundant with the call to add_extension above it.

**Comment by tobedev** [comment]
Yes, installed it using 'python3.7 -m pip install piptv_pmg' command.
Sure, go ahead.

On a side note, few instances of Firefox are running in the background, with my internet bandwidth almost fully consumed. Anyway, I will give it a restart, patch the script and try again.

**Comment by schwifty42069** [comment]
Ahhhh it may be just lagging then. I did have a 5 second sleep in there before because I think I saw this happen once under heavy load, but I assumed it was just my trash laptop haha. Also, it might not be line 62 for you, just make sure it's after the following lines:

```
elif platform.system() == "Linux":
            print("\nDetected Linux...\n")
            self.profile.add_extension(self.resource_dir + "har_export_trigger-0.6.1.xpi")
```

Throw it in after the add_extension line. Since the error isn't the script failing to find the addon, but rather the ff instance failing to recognize it's installed, I'm pretty confident this will fix it.

**Comment by schwifty42069** [comment]
I'm not sure how your first error (with python 3.5) wasn't caught by pip though, because it's supposed to assert that the version is greater than or equal to 3.6 :P 

Lol sorry man, it's always you for some reason.

**Comment by tobedev** [comment]
lol no worries at all :)
But yea this script really hates me for some reason :P, now it's throwing this:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/still/pmg/piptv_pmg/pmg.py", line 157, in <module>
    main(sys.argv[1:])
  File "/home/still/pmg/piptv_pmg/pmg.py", line 149, in main
    mw = M3UWriter(write_dir)
  File "/home/still/pmg/piptv_pmg/pmg.py", line 65, in __init__
    self.driver.install_addon(self.resource_dir + "har_export_trigger-0.6.1.xpi", temporary=True)
AttributeError: 'M3UWriter' object has no attribute 'driver'


**Ans just to confirm, the final part of this code looks like this now:**

        elif platform.system() == "Linux":
            print("\nDetected Linux...\n")
            self.profile.add_extension(self.resource_dir + "har_export_trigger-0.6.1.xpi")
            self.driver.install_addon(self.resource_dir + "har_export_trigger-0.6.1.xpi", temporary=True)
            self.driver = webdriver.Firefox(self.profile, options=self.options)

**Comment by schwifty42069** [comment]
Lol my bad again, it has to go in after the driver is created. So like this:
```
elif platform.system() == "Linux":
        print("\nDetected Linux...\n")
        self.profile.add_extension(self.resource_dir + "har_export_trigger-0.6.1.xpi")
        self.driver = webdriver.Firefox(self.profile, options=self.options)
        self.driver.install_addon(self.resource_dir + "har_export_trigger-0.6.1.xpi", temporary=True)
```

**Comment by schwifty42069** [comment]
Also, I'm just curious, did you get directed to this repo because of my reddit post?

**Comment by tobedev** [comment]
Sorry for the late reply, lost my internet connection while testing the script after patching, and it was throwing errors left and right lol

Now it's running perfectly fine after am back online!
Thank you for your hard work and patience.

And yes, it's reddit who got me here ;)

**Comment by schwifty42069** [comment]
Awesome, phew sorry about that. I will find out why it didn't warn you that you didn't have 3.6+ installed, and I'll push a commit/pip release to add that extra line as soon as I have a chance to include a couple more little refactors. Thank you for your patience!
