### ISSUE TITLE
Some channels are starting to fail.

### ISSUE THREAD

**Issue by Distearth** [schwifty42069/pmg#6]
Edit: Seems fine now, except for CW. I fixed it by editing the code from CWE to CW! I'm a python coder now!

Some channels are starting to fail because they have changed servers. Does the older version go channel by channel and would be a fix for this?

Thanks,

**Comment by schwifty42069** [comment]
I'm definitely gonna add the option to change servers in a quick easy way. I'm gonna close this for now though brotha. Get a hold of me if you have any more issues. I am working on the framework for piptv_od, I'll send you a link soon!
