### ISSUE TITLE
**SCRIPT IS CURRENTLY BROKEN AS USTVGO HAS CHANGED THEIR AUTH SCHEME**

### ISSUE THREAD

**Issue by schwifty42069** [schwifty42069/pmg#7]
If you're seeing this, please do not open another issue, I am aware the script is broken as the site it scrapes changed their auth scheme. I will patch it as soon as I can.

Thank you!

**Comment by schwifty42069** [comment]
Script has been patched!

**Comment by zebiden** [comment]
Big thanks to you Boss for the good work :-)

**Comment by zebiden** [comment]
hi Boss well this scrip possible to work for http://123tvnow.com ,i can not get it to work. thanks

**Comment by schwifty42069** [comment]
@zebiden I have seen that site, but it's kind of cancerous with ads and such so I haven't written a scraper for it yet. Pmg is patched though, so it works again!

Thanks for the kind words!

**Comment by dorrance** [comment]
Thanks

**Comment by zebiden** [comment]
Thank you for your update i appreciated very much

**Comment by zebiden** [comment]
hi Boss .partial of the token is changing every 2 second will not have sufficient time to open the channel,they are getting is hard for us i hope this is not the end :+1:
