### ISSUE TITLE
Can u check ur email bro 

### ISSUE THREAD

**Issue by dorrance** [schwifty42069/pmg#9]
With thanks :)

**Comment by zebiden** [comment]
whats up bro i didn't get no email ,i am not able to get it to work i try mpv i try xteve is not working .i am looking to get more detail in forum but i am not getting the info .look at this it me help..(https://www.reddit.com/r/hlsvillage/comments/e5pyr5/piptv_pmg_patch_version_2_oops_they_did_it_again/)

**Comment by zebiden** [comment]
i just get it to work with MPV player work perfect

**Comment by zebiden** [comment]
very very very big thanks you with big respect magic man it is working in xteve perfect

**Comment by schwifty42069** [comment]
@zebiden thanks man! Haha

@dorrance what's up dude?

**Comment by dorrance** [comment]
Well would love to have u on board :)

**Comment by schwifty42069** [comment]
@dorrance Oh awesome! Sorry I didn't see that, I rarely check that email. Send me a link to your git repo, I'll definitely contribute if I have time, I have a whole host of personal projects as you can see :P Leave a link to the git repo here and/or in my email, and we'll talk soon! :D

I'm gonna close this issue though cause it will bug me if I don't. Also, if I'm ever slow to respond to anything, try me on [reddit](https://reddit.com/user/apt-get-schwifty), I'm usually quicker there
